use_frameworks!

target 'YYPImManager_Example' do
  pod 'YYPImManager', :path => '../'

  target 'YYPImManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
